import type { Metadata } from 'next';
import './globals.css';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { getMessages } from 'next-intl/server';
import { Link } from '@/i18n/navigation';
import NextTopLoader from 'nextjs-toploader';
import { getLangDir } from 'rtl-detect';
import NextLoader from 'nextjs-rtl-loader';
import { Button } from '../../components/ui/button';
import { contentFont, headFont } from '@/utils/fonts';
import { Toaster } from '@/components/ui/sonner';
import { QueryProvider } from '@/providers/query-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  const messages = await getMessages();
  const direction = getLangDir(locale);

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      lang={locale}
      dir={direction}
      className={`${contentFont.variable} ${headFont.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {direction === 'rtl' ? (
          <NextLoader
            zIndex={99999999999999}
            color="red"
            height={6}
            showSpinner={true}
          />
        ) : (
          <NextTopLoader
            zIndex={99999999999999}
            color="blue"
            height={6}
            showSpinner={true}
          />
        )}

        <Toaster position="top-center" richColors />

        <NextIntlClientProvider locale={locale} messages={messages}>
          <QueryProvider>
            <Link href="/" className="text-blue-500">
              Home
            </Link>
            <Link href="/users" className="text-blue-500">
              Users
            </Link>
            <Link href="/login" className="text-blue-500">
              Login
            </Link>

            <Button>HELLO</Button>
            {children}
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

